import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LandingPageFive</Link>
        </li>
        <li>
          <Link to="/homeeight">HomeEight</Link>
        </li>
        <li>
          <Link to="/homesix">HomeSix</Link>
        </li>
        <li>
          <Link to="/landingpagethree">LandingPageThree</Link>
        </li>
        <li>
          <Link to="/landingpageone">LandingPageOne</Link>
        </li>
        <li>
          <Link to="/landingpagetwo">LandingPageTwo</Link>
        </li>
        <li>
          <Link to="/landingpagefour">LandingPageFour</Link>
        </li>
        <li>
          <Link to="/landingpage">LandingPage</Link>
        </li>
        <li>
          <Link to="/homenine">HomeNine</Link>
        </li>
        <li>
          <Link to="/aboutone">AboutOne</Link>
        </li>
        <li>
          <Link to="/mywork">MyWork</Link>
        </li>
        <li>
          <Link to="/services">Services</Link>
        </li>
        <li>
          <Link to="/getintouch">GetInTouch</Link>
        </li>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/imagine">Imagine</Link>
        </li>
        <li>
          <Link to="/homeseven">HomeSeven</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
        <li>
          <Link to="/banner">Banner</Link>
        </li>
        <li>
          <Link to="/homefive">HomeFive</Link>
        </li>
        <li>
          <Link to="/abouttwo">AboutTwo</Link>
        </li>
        <li>
          <Link to="/hometwo">HomeTwo</Link>
        </li>
        <li>
          <Link to="/homeone">HomeOne</Link>
        </li>
        <li>
          <Link to="/homefour">HomeFour</Link>
        </li>
        <li>
          <Link to="/homethree">HomeThree</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
